# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.github_repo }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kevin's Blog
description: Kevin's Blog

theme: jekyll-theme-cayman
# Set a path/url to a logo that will be displayed instead of the title
#logo: "/assets/images/just-the-docs.png"

# For copy button on code
enable_copy_code_button: true

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

# Enable or disable the side/mobile menu globally
# Nav menu can also be selectively enabled or disabled using page variables or the minimal layout
nav_enabled: true

# Sort order for navigation links
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Show navigation error report
nav_error_report: true # default is false/nil.

# liquid:
#   error_mode: strict
#   strict_filters: true

# Footer content
# appears at the bottom of every page's main content

# # 忽略文件
# exclude:
#   - *.md

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
# Note: the main Just the Docs site does *not* use Google Analytics.
# ga_tracking: UA-2709176-10,G-5FG1HLH3XQ
# ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)

plugins:
  - jekyll-seo-tag
  - jekyll-github-metadata
  - jekyll-include-cache
  - jekyll-sitemap

markdown: GFM
kramdown:
  math_engine: mathjax         # 明确指定 mathjax 引擎
  syntax_highlighter: rouge
  parse_block_html: true       # 允许解析 HTML 块中的内容
  input: GFM                   # 兼容 GitHub Flavored Markdown
  entity_output: as_input     # 禁止自动转义特殊字符
